In [1]:
#IMPORTING THE REQUIRED LIBRARIES
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
ds3 = pd.read_csv('countrycode.csv')
ds3

Country Code         Country
0              1           India
1             14       Australia
2             30          Brazil
3             37          Canada
4             94       Indonesia
5            148     New Zealand
6            162     Phillipines
7            166           Qatar
8            184       Singapore
9            189    South Africa
10           191       Sri Lanka
11           208          Turkey
12           214             UAE
13           215  United Kingdom
14           216   United States

In [3]:
ds2 = pd.read_csv('zomatofile.csv')
ds2

Restaurant ID           Restaurant Name  Country Code              City  \
0           6317637          Le Petit Souffle           162       Makati City   
1           6304287          Izakaya Kikufuji           162       Makati City   
2           6300002    Heat - Edsa Shangri-La           162  Mandaluyong City   
3           6318506                      Ooma           162  Mandaluyong City   
4           6314302               Sambo Kojin           162  Mandaluyong City   
...             ...                       ...           ...               ...   
9546        5915730               Naml۱ Gurme           208         ��stanbul   
9547        5908749              Ceviz A��ac۱           208         ��stanbul   
9548        5915807                     Huqqa           208         ��stanbul   
9549        5916112               A���k Kahve           208         ��stanbul   
9550        5927402  Walter's Coffee Roastery           208         ��stanbul   

                                                Address  \
0     Third Floor, Century City Mall, Kalayaan Avenu...   
1     Little Tokyo, 2277 Chino Roces Avenue, Legaspi...   
2     Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...   
3     Third Floor, Mega Fashion Hall, SM Megamall, O...   
4     Third Floor, Mega Atrium, SM Megamall, Ortigas...   
...                                                 ...   
9546  Kemanke�� Karamustafa Pa��a Mahallesi, R۱ht۱m ...   
9547  Ko��uyolu Mahallesi, Muhittin ��st�_nda�� Cadd...   
9548  Kuru�_e��me Mahallesi, Muallim Naci Caddesi, N...   
9549  Kuru�_e��me Mahallesi, Muallim Naci Caddesi, N...   
9550  Cafea��a Mahallesi, Bademalt۱ Sokak, No 21/B, ...   

                                        Locality  \
0      Century City Mall, Poblacion, Makati City   
1     Little Tokyo, Legaspi Village, Makati City   
2     Edsa Shangri-La, Ortigas, Mandaluyong City   
3         SM Megamall, Ortigas, Mandaluyong City   
4         SM Megamall, Ortigas, Mandaluyong City   
...                                          ...   
9546                                    Karak�_y   
9547                                   Ko��uyolu   
9548                                 Kuru�_e��me   
9549                                 Kuru�_e��me   
9550                                        Moda   

                                       Locality Verbose   Longitude  \
0     Century City Mall, Poblacion, Makati City, Mak...  121.027535   
1     Little Tokyo, Legaspi Village, Makati City, Ma...  121.014101   
2     Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...  121.056831   
3     SM Megamall, Ortigas, Mandaluyong City, Mandal...  121.056475   
4     SM Megamall, Ortigas, Mandaluyong City, Mandal...  121.057508   
...                                                 ...         ...   
9546                                Karak�_y, ��stanbul   28.977392   
9547                               Ko��uyolu, ��stanbul   29.041297   
9548                             Kuru�_e��me, ��stanbul   29.034640   
9549                             Kuru�_e��me, ��stanbul   29.036019   
9550                                    Moda, ��stanbul   29.026016   

       Latitude                          Cuisines  ...          Currency  \
0     14.565443        French, Japanese, Desserts  ...  Botswana Pula(P)   
1     14.553708                          Japanese  ...  Botswana Pula(P)   
2     14.581404  Seafood, Asian, Filipino, Indian  ...  Botswana Pula(P)   
3     14.585318                   Japanese, Sushi  ...  Botswana Pula(P)   
4     14.584450                  Japanese, Korean  ...  Botswana Pula(P)   
...         ...                               ...  ...               ...   
9546  41.022793                           Turkish  ...  Turkish Lira(TL)   
9547  41.009847   World Cuisine, Patisserie, Cafe  ...  Turkish Lira(TL)   
9548  41.055817            Italian, World Cuisine  ...  Turkish Lira(TL)   
9549  41.057979                   Restaurant Cafe  ...  Turkish Lira(TL)   
9550  40.9

In [4]:
ds1 = pd.merge(ds2,ds3, on="Country Code")
ds1

Restaurant ID           Restaurant Name  Country Code              City  \
0           6317637          Le Petit Souffle           162       Makati City   
1           6304287          Izakaya Kikufuji           162       Makati City   
2           6300002    Heat - Edsa Shangri-La           162  Mandaluyong City   
3           6318506                      Ooma           162  Mandaluyong City   
4           6314302               Sambo Kojin           162  Mandaluyong City   
...             ...                       ...           ...               ...   
9546        5915730               Naml۱ Gurme           208         ��stanbul   
9547        5908749              Ceviz A��ac۱           208         ��stanbul   
9548        5915807                     Huqqa           208         ��stanbul   
9549        5916112               A���k Kahve           208         ��stanbul   
9550        5927402  Walter's Coffee Roastery           208         ��stanbul   

                                                Address  \
0     Third Floor, Century City Mall, Kalayaan Avenu...   
1     Little Tokyo, 2277 Chino Roces Avenue, Legaspi...   
2     Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...   
3     Third Floor, Mega Fashion Hall, SM Megamall, O...   
4     Third Floor, Mega Atrium, SM Megamall, Ortigas...   
...                                                 ...   
9546  Kemanke�� Karamustafa Pa��a Mahallesi, R۱ht۱m ...   
9547  Ko��uyolu Mahallesi, Muhittin ��st�_nda�� Cadd...   
9548  Kuru�_e��me Mahallesi, Muallim Naci Caddesi, N...   
9549  Kuru�_e��me Mahallesi, Muallim Naci Caddesi, N...   
9550  Cafea��a Mahallesi, Bademalt۱ Sokak, No 21/B, ...   

                                        Locality  \
0      Century City Mall, Poblacion, Makati City   
1     Little Tokyo, Legaspi Village, Makati City   
2     Edsa Shangri-La, Ortigas, Mandaluyong City   
3         SM Megamall, Ortigas, Mandaluyong City   
4         SM Megamall, Ortigas, Mandaluyong City   
...                                          ...   
9546                                    Karak�_y   
9547                                   Ko��uyolu   
9548                                 Kuru�_e��me   
9549                                 Kuru�_e��me   
9550                                        Moda   

                                       Locality Verbose   Longitude  \
0     Century City Mall, Poblacion, Makati City, Mak...  121.027535   
1     Little Tokyo, Legaspi Village, Makati City, Ma...  121.014101   
2     Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...  121.056831   
3     SM Megamall, Ortigas, Mandaluyong City, Mandal...  121.056475   
4     SM Megamall, Ortigas, Mandaluyong City, Mandal...  121.057508   
...                                                 ...         ...   
9546                                Karak�_y, ��stanbul   28.977392   
9547                               Ko��uyolu, ��stanbul   29.041297   
9548                             Kuru�_e��me, ��stanbul   29.034640   
9549                             Kuru�_e��me, ��stanbul   29.036019   
9550                                    Moda, ��stanbul   29.026016   

       Latitude                          Cuisines  ...  Has Table booking  \
0     14.565443        French, Japanese, Desserts  ...                Yes   
1     14.553708                          Japanese  ...                Yes   
2     14.581404  Seafood, Asian, Filipino, Indian  ...                Yes   
3     14.585318                   Japanese, Sushi  ...                 No   
4     14.584450                  Japanese, Korean  ...                Yes   
...         ...                               ...  ...                ...   
9546  41.022793                           Turkish  ...                 No   
9547  41.009847   World Cuisine, Patisserie, Cafe  ...                 No   
9548  41.055817            Italian, World Cuisine  ...                 No   
9549  41.057979                   Restaurant Cafe  ...                 No   

In [5]:
ds1=ds1.drop(columns=['Country Code','Address','Locality','Longitude','Latitude','Restaurant Name','City','Locality Verbose','Is delivering now','Switch to order menu','Rating color'],axis=1)
ds1

Restaurant ID                          Cuisines  Average Cost for two  \
0           6317637        French, Japanese, Desserts                  1100   
1           6304287                          Japanese                  1200   
2           6300002  Seafood, Asian, Filipino, Indian                  4000   
3           6318506                   Japanese, Sushi                  1500   
4           6314302                  Japanese, Korean                  1500   
...             ...                               ...                   ...   
9546        5915730                           Turkish                    80   
9547        5908749   World Cuisine, Patisserie, Cafe                   105   
9548        5915807            Italian, World Cuisine                   170   
9549        5916112                   Restaurant Cafe                   120   
9550        5927402                              Cafe                    55   

              Currency Has Table booking Has Online delivery  Price range  \
0     Botswana Pula(P)               Yes                  No            3   
1     Botswana Pula(P)               Yes                  No            3   
2     Botswana Pula(P)               Yes                  No            4   
3     Botswana Pula(P)                No                  No            4   
4     Botswana Pula(P)               Yes                  No            4   
...                ...               ...                 ...          ...   
9546  Turkish Lira(TL)                No                  No            3   
9547  Turkish Lira(TL)                No                  No            3   
9548  Turkish Lira(TL)                No                  No            4   
9549  Turkish Lira(TL)                No                  No            4   
9550  Turkish Lira(TL)                No                  No            2   

      Aggregate rating Rating text  Votes      Country  
0                  4.8   Excellent    314  Phillipines  
1                  4.5   Excellent    591  Phillipines  
2                  4.4   Very Good    270  Phillipines  
3                  4.9   Excellent    365  Phillipines  
4                  4.8   Excellent    229  Phillipines  
...                ...         ...    ...          ...  
9546               4.1   Very Good    788       Turkey  
9547               4.2   Very Good   1034       Turkey  
9548               3.7        Good    661       Turkey  
9549               4.0   Very Good    901       Turkey  
9550               4.0   Very Good    591       Turkey  

[9551 rows x 11 columns]

In [6]:
ds1.set_index("Restaurant ID", inplace = True)

In [37]:
#CHECKING FOR NULL VALUES
ds1.isnull().sum()

Cuisines                9
Average Cost for two    0
Currency                0
Has Table booking       0
Has Online delivery     0
Price range             0
Aggregate rating        0
Rating text             0
Votes                   0
Country                 0
dtype: int64

In [38]:
print(ds1['Cuisines'].mode())

0    North Indian
Name: Cuisines, dtype: object


In [39]:
#HANDLING NULL VALUES
#Applying Mode imputation technique 
ds1['Cuisines'].fillna(ds1['Cuisines'].mode()[0],inplace=True)
ds1

Cuisines  Average Cost for two  \
Restaurant ID                                                           
6317637              French, Japanese, Desserts                  1100   
6304287                                Japanese                  1200   
6300002        Seafood, Asian, Filipino, Indian                  4000   
6318506                         Japanese, Sushi                  1500   
6314302                        Japanese, Korean                  1500   
...                                         ...                   ...   
5915730                                 Turkish                    80   
5908749         World Cuisine, Patisserie, Cafe                   105   
5915807                  Italian, World Cuisine                   170   
5916112                         Restaurant Cafe                   120   
5927402                                    Cafe                    55   

                       Currency Has Table booking Has Online delivery  \
Restaurant ID                                                           
6317637        Botswana Pula(P)               Yes                  No   
6304287        Botswana Pula(P)               Yes                  No   
6300002        Botswana Pula(P)               Yes                  No   
6318506        Botswana Pula(P)                No                  No   
6314302        Botswana Pula(P)               Yes                  No   
...                         ...               ...                 ...   
5915730        Turkish Lira(TL)                No                  No   
5908749        Turkish Lira(TL)                No                  No   
5915807        Turkish Lira(TL)                No                  No   
5916112        Turkish Lira(TL)                No                  No   
5927402        Turkish Lira(TL)                No                  No   

               Price range  Aggregate rating Rating text  Votes      Country  
Restaurant ID                                                                 
6317637                  3               4.8   Excellent    314  Phillipines  
6304287                  3               4.5   Excellent    591  Phillipines  
6300002                  4               4.4   Very Good    270  Phillipines  
6318506                  4               4.9   Excellent    365  Phillipines  
6314302                  4               4.8   Excellent    229  Phillipines  
...                    ...               ...         ...    ...          ...  
5915730                  3               4.1   Very Good    788       Turkey  
5908749                  3               4.2   Very Good   1034       Turkey  
5915807                  4               3.7        Good    661       Turkey  
5916112                  4               4.0   Very Good    901       Turkey  
5927402                  2               4.0   Very Good    591       Turkey  

[9551 rows x 10 columns]

In [40]:
#CHECKING FOR NULL VALUES
ds1.isnull().sum()

Cuisines                0
Average Cost for two    0
Currency                0
Has Table booking       0
Has Online delivery     0
Price range             0
Aggregate rating        0
Rating text             0
Votes                   0
Country                 0
dtype: int64

In [41]:
ds1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9551 entries, 6317637 to 5927402
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   Cuisines              9551 non-null   object 
 1   Average Cost for two  9551 non-null   int64  
 2   Currency              9551 non-null   object 
 3   Has Table booking     9551 non-null   object 
 4   Has Online delivery   9551 non-null   object 
 5   Price range           9551 non-null   int64  
 6   Aggregate rating      9551 non-null   float64
 7   Rating text           9551 non-null   object 
 8   Votes                 9551 non-null   int64  
 9   Country               9551 non-null   object 
dtypes: float64(1), int64(3), object(6)
memory usage: 820.8+ KB


In [42]:
#CHECKING FOR THE COUNT OF EVERY VALUES IN EACH COULMNS
for i in ds1.columns:
    print(ds1[i].value_counts())

North Indian                                             945
North Indian, Chinese                                    511
Fast Food                                                354
Chinese                                                  354
North Indian, Mughlai                                    334
                                                        ... 
Bengali, Fast Food                                         1
North Indian, Rajasthani, Asian                            1
Chinese, Thai, Malaysian, Indonesian                       1
Bakery, Desserts, North Indian, Bengali, South Indian      1
Italian, World Cuisine                                     1
Name: Cuisines, Length: 1825, dtype: int64
500       900
300       897
400       857
200       687
600       652
         ... 
8000        1
2350        1
150000      1
70000       1
545         1
Name: Average Cost for two, Length: 140, dtype: int64
Indian Rupees(Rs.)        8652
Dollar($)                  482
Pounds(��)      

In [43]:
ds1.nunique()

Cuisines                1825
Average Cost for two     140
Currency                  12
Has Table booking          2
Has Online delivery        2
Price range                4
Aggregate rating          33
Rating text                6
Votes                   1012
Country                   15
dtype: int64

In [7]:
ds1.describe()

Average Cost for two  Price range  Aggregate rating         Votes
count           9551.000000  9551.000000       9551.000000   9551.000000
mean            1199.210763     1.804837          2.666370    156.909748
std            16121.183073     0.905609          1.516378    430.169145
min                0.000000     1.000000          0.000000      0.000000
25%              250.000000     1.000000          2.500000      5.000000
50%              400.000000     2.000000          3.200000     31.000000
75%              700.000000     2.000000          3.700000    131.000000
max           800000.000000     4.000000          4.900000  10934.000000

- There are no null values in the dataset
- Huge difference mean and median indicates presence of skewness
- Huge difference between 75% and max values and hence outliers are present

In [8]:
#SEPERATING CATEGORICAL AND NUMERICAL COLUMNS
cat_col=[]
num_col=[]
for i in ds1.dtypes.index:
    if ds1.dtypes[i]=="object":
        cat_col.append(i)
    else:
        num_col.append(i)
print(cat_col)
print(num_col)

['Cuisines', 'Currency', 'Has Table booking', 'Has Online delivery', 'Rating text', 'Country']
['Average Cost for two', 'Price range', 'Aggregate rating', 'Votes']


In [9]:
#CHECKING FOR OUTLIERS
from scipy.stats import zscore
f=ds1[['Votes','Aggregate rating','Price range','Average Cost for two']]
z=np.abs(zscore(f))
z

Votes  Aggregate rating  Price range  Average Cost for two
Restaurant ID                                                               
6317637        0.365202          1.407131     1.319803              0.006154
6304287        1.009168          1.209281     1.319803              0.000049
6300002        0.262911          1.143331     2.424090              0.173743
6318506        0.483766          1.473081     2.424090              0.018659
6314302        0.167595          1.407131     2.424090              0.018659
...                 ...               ...          ...                   ...
5915730        1.467151          0.945480     1.319803              0.069428
5908749        2.039049          1.011430     1.319803              0.067878
5915807        1.171903          0.681680     2.424090              0.063845
5916112        1.729853          0.879530     2.424090              0.066947
5927402        1.009168          0.879530     0.215516              0.070979

[9551 rows x 4 columns]

In [10]:
print(np.where(z>3))

(array([ 102,  336,  341,  342,  343,  350,  352,  409,  429,  454,  458,
        468,  469,  470,  472,  585,  591,  600,  644,  726,  727,  728,
        731,  735,  736,  739,  743,  793,  805,  807,  811,  813,  814,
        815,  817,  821,  824, 1144, 1147, 1163, 1235, 1247, 1248, 1251,
       1252, 1253, 1255, 1256, 1258, 1464, 1554, 1555, 1839, 1861, 1866,
       2300, 2302, 2304, 2307, 2311, 2314, 2338, 2344, 2402, 2404, 2406,
       2409, 2410, 2411, 2412, 2413, 2414, 2416, 2480, 2483, 2484, 2485,
       2488, 2490, 2492, 2495, 2499, 2635, 2880, 3005, 3008, 3013, 3016,
       3018, 3025, 3026, 3028, 3033, 3041, 3049, 3055, 3056, 3057, 3060,
       3068, 3075, 3080, 3083, 3085, 3093, 3094, 3095, 3101, 3107, 3110,
       3112, 3115, 3116, 3117, 3118, 3119, 3316, 3319, 3336, 3337, 3338,
       3438, 3588, 3589, 3599, 3601, 3605, 3976, 3983, 3984, 3986, 3992,
       3993, 3994, 3998, 4087, 4162, 4178, 4320, 4386, 4638, 4639, 4649,
       4673, 5007, 5026, 6144, 6317, 6534, 6659, 6

In [11]:
#REMOVING OUTLIERS
ds6=ds1[(z<3).all(axis=1)]
ds6

Cuisines  Average Cost for two  \
Restaurant ID                                                           
6317637              French, Japanese, Desserts                  1100   
6304287                                Japanese                  1200   
6300002        Seafood, Asian, Filipino, Indian                  4000   
6318506                         Japanese, Sushi                  1500   
6314302                        Japanese, Korean                  1500   
...                                         ...                   ...   
5915730                                 Turkish                    80   
5908749         World Cuisine, Patisserie, Cafe                   105   
5915807                  Italian, World Cuisine                   170   
5916112                         Restaurant Cafe                   120   
5927402                                    Cafe                    55   

                       Currency Has Table booking Has Online delivery  \
Restaurant ID                                                           
6317637        Botswana Pula(P)               Yes                  No   
6304287        Botswana Pula(P)               Yes                  No   
6300002        Botswana Pula(P)               Yes                  No   
6318506        Botswana Pula(P)                No                  No   
6314302        Botswana Pula(P)               Yes                  No   
...                         ...               ...                 ...   
5915730        Turkish Lira(TL)                No                  No   
5908749        Turkish Lira(TL)                No                  No   
5915807        Turkish Lira(TL)                No                  No   
5916112        Turkish Lira(TL)                No                  No   
5927402        Turkish Lira(TL)                No                  No   

               Price range  Aggregate rating Rating text  Votes      Country  
Restaurant ID                                                                 
6317637                  3               4.8   Excellent    314  Phillipines  
6304287                  3               4.5   Excellent    591  Phillipines  
6300002                  4               4.4   Very Good    270  Phillipines  
6318506                  4               4.9   Excellent    365  Phillipines  
6314302                  4               4.8   Excellent    229  Phillipines  
...                    ...               ...         ...    ...          ...  
5915730                  3               4.1   Very Good    788       Turkey  
5908749                  3               4.2   Very Good   1034       Turkey  
5915807                  4               3.7        Good    661       Turkey  
5916112                  4               4.0   Very Good    901       Turkey  
5927402                  2               4.0   Very Good    591       Turkey  

[9362 rows x 10 columns]

In [12]:
ds6.skew()

Average Cost for two    3.619524
Price range             0.933571
Aggregate rating       -0.940907
Votes                   3.216882
dtype: float64

In [13]:
#REMOVING SKEWNESS USING CUBEROOT METHOD
ds6[['Votes']] = np.cbrt(ds6[['Votes']])
ds6.skew()

Average Cost for two    3.619524
Price range             0.933571
Aggregate rating       -0.940907
Votes                   0.690515
dtype: float64

In [14]:
# LABEL ENCODING TECHNIQUE
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
for i in cat_col:
    ds6[i]=le.fit_transform(ds6[i].astype(str))
ds6

Cuisines  Average Cost for two  Currency  Has Table booking  \
Restaurant ID                                                                
6317637             881                  1100         0                  1   
6304287            1063                  1200         0                  1   
6300002            1611                  4000         0                  1   
6318506            1078                  1500         0                  0   
6314302            1074                  1500         0                  1   
...                 ...                   ...       ...                ...   
5915730            1748                    80        10                  0   
5908749            1758                   105        10                  0   
5915807            1062                   170        10                  0   
5916112            1597                   120        10                  0   
5927402             319                    55        10                  0   

               Has Online delivery  Price range  Aggregate rating  \
Restaurant ID                                                       
6317637                          0            3               4.8   
6304287                          0            3               4.5   
6300002                          0            4               4.4   
6318506                          0            4               4.9   
6314302                          0            4               4.8   
...                            ...          ...               ...   
5915730                          0            3               4.1   
5908749                          0            3               4.2   
5915807                          0            4               3.7   
5916112                          0            4               4.0   
5927402                          0            2               4.0   

               Rating text      Votes  Country  
Restaurant ID                                   
6317637                  1   6.796884        5  
6304287                  1   8.391942        5  
6300002                  5   6.463304        5  
6318506                  1   7.146569        5  
6314302                  1   6.118033        5  
...                    ...        ...      ...  
5915730                  5   9.236528       10  
5908749                  5  10.112073       10  
5915807                  2   8.710983       10  
5916112                  5   9.658468       10  
5927402                  5   8.391942       10  

[9362 rows x 10 columns]

In [15]:
ds6.corr()

Cuisines  Average Cost for two  Currency  \
Cuisines              1.000000              0.040496  0.079960   
Average Cost for two  0.040496              1.000000  0.098031   
Currency              0.079960              0.098031  1.000000   
Has Table booking     0.052416              0.594594  0.006740   
Has Online delivery  -0.016085              0.093108  0.027284   
Price range          -0.006319              0.668157  0.040494   
Aggregate rating     -0.080506              0.237984 -0.039970   
Rating text          -0.084057              0.033707 -0.013184   
Votes                -0.069660              0.305831 -0.052018   
Country              -0.120820             -0.206629 -0.194558   

                      Has Table booking  Has Online delivery  Price range  \
Cuisines                       0.052416            -0.016085    -0.006319   
Average Cost for two           0.594594             0.093108     0.668157   
Currency                       0.006740             0.027284     0.040494   
Has Table booking              1.000000             0.091947     0.503988   
Has Online delivery            0.091947             1.000000     0.079068   
Price range                    0.503988             0.079068     1.000000   
Aggregate rating               0.184989             0.229227     0.426773   
Rating text                    0.028723            -0.085968     0.147713   
Votes                          0.279458             0.256064     0.514131   
Country                       -0.060202            -0.136909     0.170036   

                      Aggregate rating  Rating text     Votes   Country  
Cuisines                     -0.080506    -0.084057 -0.069660 -0.120820  
Average Cost for two          0.237984     0.033707  0.305831 -0.206629  
Currency                     -0.039970    -0.013184 -0.052018 -0.194558  
Has Table booking             0.184989     0.028723  0.279458 -0.060202  
Has Online delivery           0.229227    -0.085968  0.256064 -0.136909  
Price range                   0.426773     0.147713  0.514131  0.170036  
Aggregate rating              1.000000    -0.206530  0.757362  0.252549  
Rating text                  -0.206530     1.000000  0.120744  0.209306  
Votes                         0.757362     0.120744  1.000000  0.335706  
Country                       0.252549     0.209306  0.335706  1.000000

In [16]:
#SEPERATING INDEPENDENT VARIABLES AND TARGET
x1 = ds6.drop('Average Cost for two',axis=1)
y1 = ds6['Average Cost for two']
print(x1)

               Cuisines  Currency  Has Table booking  Has Online delivery  \
Restaurant ID                                                               
6317637             881         0                  1                    0   
6304287            1063         0                  1                    0   
6300002            1611         0                  1                    0   
6318506            1078         0                  0                    0   
6314302            1074         0                  1                    0   
...                 ...       ...                ...                  ...   
5915730            1748        10                  0                    0   
5908749            1758        10                  0                    0   
5915807            1062        10                  0                    0   
5916112            1597        10                  0                    0   
5927402             319        10                  0                    0   

In [17]:
y1

Restaurant ID
6317637    1100
6304287    1200
6300002    4000
6318506    1500
6314302    1500
           ... 
5915730      80
5908749     105
5915807     170
5916112     120
5927402      55
Name: Average Cost for two, Length: 9362, dtype: int64

In [18]:
#SCALING TO REMOVE BIASNESS - STANDARD SCALING
from sklearn.preprocessing import StandardScaler
st=StandardScaler()
x1=st.fit_transform(x1)
x1

array([[-0.14151352, -4.92807321,  2.74626488, ..., -0.45191551,
         1.37372643,  0.56840201],
       [ 0.22521291, -4.92807321,  2.74626488, ..., -0.45191551,
         2.02735957,  0.56840201],
       [ 1.32942217, -4.92807321,  2.74626488, ...,  1.932324  ,
         1.23702974,  0.56840201],
       ...,
       [ 0.22319793,  7.54364344, -0.36413094, ...,  0.14414437,
         2.15809798,  2.66806251],
       [ 1.30121245,  7.54364344, -0.36413094, ...,  1.932324  ,
         2.54636476,  2.66806251],
       [-1.27393252,  7.54364344, -0.36413094, ...,  1.932324  ,
         2.02735957,  2.66806251]])

In [19]:
x1=pd.DataFrame(data=x1)
x1

0         1         2         3         4         5         6  \
0    -0.141514 -4.928073  2.746265 -0.586149  1.359625  1.429678 -0.451916   
1     0.225213 -4.928073  2.746265 -0.586149  1.359625  1.231562 -0.451916   
2     1.329422 -4.928073  2.746265 -0.586149  2.476579  1.165524  1.932324   
3     0.255438 -4.928073 -0.364131 -0.586149  2.476579  1.495717 -0.451916   
4     0.247378 -4.928073  2.746265 -0.586149  2.476579  1.429678 -0.451916   
...        ...       ...       ...       ...       ...       ...       ...   
9357  1.605474  7.543643 -0.364131 -0.586149  1.359625  0.967408  1.932324   
9358  1.625624  7.543643 -0.364131 -0.586149  1.359625  1.033446  1.932324   
9359  0.223198  7.543643 -0.364131 -0.586149  2.476579  0.703253  0.144144   
9360  1.301212  7.543643 -0.364131 -0.586149  2.476579  0.901369  1.932324   
9361 -1.273933  7.543643 -0.364131 -0.586149  0.242671  0.901369  1.932324   

             7         8  
0     1.373726  0.568402  
1     2.027360  0.568402  
2     1.237030  0.568402  
3     1.517023  0.568402  
4     1.095542  0.568402  
...        ...       ...  
9357  2.373459  2.668063  
9358  2.732246  2.668063  
9359  2.158098  2.668063  
9360  2.546365  2.668063  
9361  2.027360  2.668063  

[9362 rows x 9 columns]

In [20]:
from statsmodels.stats.outliers_influence import variance_inflation_factor
vif = pd.DataFrame()
vif["VIF Factor"] = [variance_inflation_factor(x1.values, i) for i in range(x1.shape[1])]
vif["features"] = x1.columns
vif

VIF Factor  features
0    1.034552         0
1    1.053020         1
2    1.412942         2
3    1.151768         3
4    1.778278         4
5    3.108004         5
6    1.396414         6
7    3.309567         7
8    1.330369         8

# MODELLING - AVERAGE COST FOR TWO AS TARGET

In [21]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score

In [22]:
x1_train,x1_test,y1_train,y1_test=train_test_split(x1,y1,test_size=0.40,random_state=42)

In [23]:
#LINEAR REGRESSION
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_val_score,KFold
m1=LinearRegression()
m1.fit(x1_train,y1_train)
trainprediction1=m1.predict(x1_train)
print(r2_score(y1_train,trainprediction1))
testprediction1=m1.predict(x1_test)
print(r2_score(y1_test,testprediction1))
kfold=KFold(n_splits=5,shuffle=True)
score1=cross_val_score(m1,x1,y1,cv=kfold)
print(score1)
print(score1.mean())
print((r2_score(y1_test,testprediction1)-(score1.mean())))

0.6112801847461311
0.6204318620890104
[0.60829887 0.63891451 0.60272182 0.5937954  0.6297678 ]
0.6146996801234871
0.005732181965523275


In [24]:
#ADA BOOST REGRESSION
from sklearn.ensemble import AdaBoostRegressor
m2=AdaBoostRegressor()
m2.fit(x1_train,y1_train)
trainprediction2=m2.predict(x1_train)
print(r2_score(y1_train,trainprediction2))
testprediction2=m2.predict(x1_test)
print(r2_score(y1_test,testprediction2))
kfold=KFold(n_splits=5,shuffle=True)
score2=cross_val_score(m2,x1,y1,cv=kfold)
print(score2)
print(score2.mean())
print((r2_score(y1_test,testprediction2)-(score2.mean())))

0.6815564143314004
0.6603191315935626
[0.61533469 0.69667635 0.68554665 0.55591859 0.60642256]
0.6319797670604057
0.028339364533156886


In [25]:
#GRADIENT BOOST REGRESSION
from sklearn.ensemble import GradientBoostingRegressor
m3=AdaBoostRegressor()
m3.fit(x1_train,y1_train)
trainprediction3=m3.predict(x1_train)
print(r2_score(y1_train,trainprediction3))
testprediction3=m3.predict(x1_test)
print(r2_score(y1_test,testprediction3))
kfold=KFold(n_splits=5,shuffle=True)
score3=cross_val_score(m3,x1,y1,cv=kfold)
print(score3)
print(score3.mean())
print((r2_score(y1_test,testprediction3)-(score3.mean())))

0.6929843261310629
0.666725268969576
[0.6055398  0.70269424 0.53380457 0.63785815 0.66939173]
0.629857700515695
0.03686756845388095


In [26]:
#RANDOM FOREST REGRESSION
from sklearn.ensemble import RandomForestRegressor
m4=RandomForestRegressor()
m4.fit(x1_train,y1_train)
trainprediction4=m4.predict(x1_train)
print(r2_score(y1_train,trainprediction4))
testprediction4=m4.predict(x1_test)
print(r2_score(y1_test,testprediction4))
kfold=KFold(n_splits=5,shuffle=True)
score4=cross_val_score(m4,x1,y1,cv=kfold)
print(score4)
print(score4.mean())
print((r2_score(y1_test,testprediction4)-(score4.mean())))

0.971569052276945
0.8091797857568052
[0.82340828 0.80453863 0.85213577 0.84250086 0.7816393 ]
0.8208445680693028
-0.011664782312497679


In [27]:
#DECISION TREE REGRESSION
from sklearn.tree import DecisionTreeRegressor
m5=DecisionTreeRegressor()
m5.fit(x1_train,y1_train)
trainprediction5=m5.predict(x1_train)
print(r2_score(y1_train,trainprediction5))
testprediction5=m5.predict(x1_test)
print(r2_score(y1_test,testprediction5))
kfold=KFold(n_splits=5,shuffle=True)
score5=cross_val_score(m5,x1,y1,cv=kfold)
print(score5)
print(score5.mean())
print((r2_score(y1_test,testprediction5)-(score5.mean())))

0.9964495092561141
0.6019378001135514
[0.7805614  0.62607    0.69399514 0.75723134 0.70864117]
0.7132998089829299
-0.11136200886937853


In [28]:
#SVR
from sklearn.svm import SVR
m6=SVR()
m6.fit(x1_train,y1_train)
trainprediction6=m6.predict(x1_train)
print(r2_score(y1_train,trainprediction6))
testprediction6=m6.predict(x1_test)
print(r2_score(y1_test,testprediction6))
kfold=KFold(n_splits=5,shuffle=True)
score6=cross_val_score(m6,x1,y1,cv=kfold)
print(score6)
print(score6.mean())
print((r2_score(y1_test,testprediction6)-(score6.mean())))

0.2679948482380049
0.2738910385467309
[0.32964269 0.36404676 0.31960304 0.31753507 0.33006767]
0.3321790468749645
-0.05828800832823361


In [29]:
#KNN
from sklearn.neighbors import KNeighborsRegressor
m7=KNeighborsRegressor()
m7.fit(x1_train,y1_train)
trainprediction7=m7.predict(x1_train)
print(r2_score(y1_train,trainprediction7))
testprediction7=m7.predict(x1_test)
print(r2_score(y1_test,testprediction7))
kfold=KFold(n_splits=5,shuffle=True)
score7=cross_val_score(m7,x1,y1,cv=kfold)
print(score7)
print(score7.mean())
print((r2_score(y1_test,testprediction7)-(score7.mean())))

0.8525184701494444
0.7948516086982602
[0.77453269 0.77782567 0.80386982 0.75634453 0.81282926]
0.7850803913952245
0.009771217303035762


In [32]:
from sklearn.linear_model import BayesianRidge
model=BayesianRidge()
model.fit(x1_train,y1_train)
trainprediction=model.predict(x1_train)
print(r2_score(y1_train,trainprediction))
testprediction=model.predict(x1_test)
print(r2_score(y1_test,testprediction))
kfold=KFold(n_splits=5,shuffle=True)
score111=cross_val_score(model,x1,y1,cv=kfold)
print(score111)
print(score111.mean())
print((r2_score(y1_test,testprediction1)-(score111.mean())))

0.611279275222129
0.6204781982734495
[0.6307051  0.6401783  0.557916   0.59930171 0.63079058]
0.611778338330159
0.008653523758851311


In [34]:
from sklearn.linear_model import Ridge
ridge=Ridge(alpha=10,max_iter=1000,tol=0.1)
ridge.fit(x1_train,y1_train)
trainprediction11=ridge.predict(x1_train)
print(r2_score(y1_train,trainprediction11))
testprediction11=ridge.predict(x1_test)
print(r2_score(y1_test,testprediction11))
kfold=KFold(n_splits=5,shuffle=True)
score22=cross_val_score(ridge,x1,y1,cv=kfold)
print(score22)
print(score22.mean())
print((r2_score(y1_test,testprediction11)-(score22.mean())))

0.6112783358240266
0.62049733463768
[0.5996935  0.58771901 0.62982612 0.62749865 0.62726812]
0.6144010787322717
0.006096255905408299


In [36]:
from sklearn.linear_model import Lasso
lasso=Lasso(alpha=0.0001,max_iter=1000,tol=0.1)
lasso.fit(x1_train,y1_train)
trainprediction666=lasso.predict(x1_train)
print(r2_score(y1_train,trainprediction666))
testprediction666=lasso.predict(x1_test)
print(r2_score(y1_test,testprediction666))
kfold=KFold(n_splits=5,shuffle=True)
score666=cross_val_score(lasso,x1,y1,cv=kfold)
print(score666)
print(score666.mean())
print((r2_score(y1_test,testprediction666)-(score666.mean())))

0.6112801847439022
0.6204318260125568
[0.60982027 0.63338289 0.60444113 0.62290297 0.59862536]
0.6138345244326721
0.006597301579884696


RANDOM FOREST REGRESSOR has been selected as the best model

In [44]:
from sklearn.model_selection import GridSearchCV
parameters={'n_estimators':[10,50,100],'n_jobs':[-1,1],'random_state':[10,12,42,50],'criterion':["squared_error","absolute_error","friedman_mse","poisson"],'max_features':['sqrt','log2']}
gridsearchcv=GridSearchCV(RandomForestRegressor(),parameters,cv=5)
gridsearchcv.fit(x1_train,y1_train)                      

GridSearchCV(cv=5, estimator=RandomForestRegressor(),
             param_grid={'criterion': ['squared_error', 'absolute_error',
                                       'friedman_mse', 'poisson'],
                         'max_features': ['sqrt', 'log2'],
                         'n_estimators': [10, 50, 100], 'n_jobs': [-1, 1],
                         'random_state': [10, 12, 42, 50]})

In [45]:
gridsearchcv.best_params_

{'criterion': 'absolute_error',
 'max_features': 'sqrt',
 'n_estimators': 100,
 'n_jobs': -1,
 'random_state': 10}

In [46]:
best_model=RandomForestRegressor(criterion='absolute_error',max_features='sqrt',n_estimators=100,n_jobs=-1,random_state=10)
best_model.fit(x1_train,y1_train)
prediction=best_model.predict(x1_test)
print(r2_score(y1_test,prediction))

0.82986541158798


In [47]:
#SAVING THE BEST MODEL
import joblib
joblib.dump(best_model,"zomato.obj")

['zomato.obj']

In [48]:
reload=joblib.load('zomato.obj')
reload.predict(x1_test)

array([ 633.5, 3110. , 2598. , ..., 1355.5,  599. , 1237.5])

In [49]:
def predict(zomato):
    zomato=zomato.reshape(1,-1)
    pred=best_model.predict(zomato)
    print(pred)
zomato=np.array([-0.141514,-4.928073,2.746265,-0.586149,1.359625,1.429678,-0.451916,1.373726,0.568402])
predict(zomato)

[1109.65]


# MODELLING - PRICE RANGE AS TARGET

In [51]:
#SEPERATING INDEPENDENT VARIABLES AND TARGET
x11 = ds6.drop('Price range',axis=1)
y11 = ds6['Price range']
print(x11)

               Cuisines  Average Cost for two  Currency  Has Table booking  \
Restaurant ID                                                                
6317637             881                  1100         0                  1   
6304287            1063                  1200         0                  1   
6300002            1611                  4000         0                  1   
6318506            1078                  1500         0                  0   
6314302            1074                  1500         0                  1   
...                 ...                   ...       ...                ...   
5915730            1748                    80        10                  0   
5908749            1758                   105        10                  0   
5915807            1062                   170        10                  0   
5916112            1597                   120        10                  0   
5927402             319                    55        10         

In [52]:
y11

Restaurant ID
6317637    3
6304287    3
6300002    4
6318506    4
6314302    4
          ..
5915730    3
5908749    3
5915807    4
5916112    4
5927402    2
Name: Price range, Length: 9362, dtype: int64

In [53]:
#SCALING TO REMOVE BIASNESS - STANDARD SCALING
from sklearn.preprocessing import StandardScaler
st=StandardScaler()
x11=st.fit_transform(x11)
x11

array([[-0.14151352,  0.89672919, -4.92807321, ..., -0.45191551,
         1.37372643,  0.56840201],
       [ 0.22521291,  1.06598109, -4.92807321, ..., -0.45191551,
         2.02735957,  0.56840201],
       [ 1.32942217,  5.80503434, -4.92807321, ...,  1.932324  ,
         1.23702974,  0.56840201],
       ...,
       [ 0.22319793, -0.6773135 ,  7.54364344, ...,  0.14414437,
         2.15809798,  2.66806251],
       [ 1.30121245, -0.76193945,  7.54364344, ...,  1.932324  ,
         2.54636476,  2.66806251],
       [-1.27393252, -0.87195318,  7.54364344, ...,  1.932324  ,
         2.02735957,  2.66806251]])

In [54]:
x11=pd.DataFrame(data=x11)
x11

0         1         2         3         4         5         6  \
0    -0.141514  0.896729 -4.928073  2.746265 -0.586149  1.429678 -0.451916   
1     0.225213  1.065981 -4.928073  2.746265 -0.586149  1.231562 -0.451916   
2     1.329422  5.805034 -4.928073  2.746265 -0.586149  1.165524  1.932324   
3     0.255438  1.573737 -4.928073 -0.364131 -0.586149  1.495717 -0.451916   
4     0.247378  1.573737 -4.928073  2.746265 -0.586149  1.429678 -0.451916   
...        ...       ...       ...       ...       ...       ...       ...   
9357  1.605474 -0.829640  7.543643 -0.364131 -0.586149  0.967408  1.932324   
9358  1.625624 -0.787327  7.543643 -0.364131 -0.586149  1.033446  1.932324   
9359  0.223198 -0.677313  7.543643 -0.364131 -0.586149  0.703253  0.144144   
9360  1.301212 -0.761939  7.543643 -0.364131 -0.586149  0.901369  1.932324   
9361 -1.273933 -0.871953  7.543643 -0.364131 -0.586149  0.901369  1.932324   

             7         8  
0     1.373726  0.568402  
1     2.027360  0.568402  
2     1.237030  0.568402  
3     1.517023  0.568402  
4     1.095542  0.568402  
...        ...       ...  
9357  2.373459  2.668063  
9358  2.732246  2.668063  
9359  2.158098  2.668063  
9360  2.546365  2.668063  
9361  2.027360  2.668063  

[9362 rows x 9 columns]

In [55]:
from statsmodels.stats.outliers_influence import variance_inflation_factor
vif = pd.DataFrame()
vif["VIF Factor"] = [variance_inflation_factor(x11.values, i) for i in range(x11.shape[1])]
vif["features"] = x11.columns
vif

VIF Factor  features
0    1.034068         0
1    1.800053         1
2    1.050567         2
3    1.590164         3
4    1.153876         4
5    3.041017         5
6    1.368672         6
7    3.288027         7
8    1.464643         8

In [56]:
y11.value_counts()

1    4437
2    3075
3    1297
4     553
Name: Price range, dtype: int64

In [57]:
#BALANCING THE DATA SET
from imblearn.over_sampling import SMOTE
SM=SMOTE()
x11,y11=SM.fit_resample(x11,y11)
y11.value_counts()

3    4437
4    4437
2    4437
1    4437
Name: Price range, dtype: int64

In [58]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import roc_curve
from sklearn.model_selection import cross_val_score

In [59]:
x11_train,x11_test,y11_train,y11_test=train_test_split(x11,y11,test_size=0.30,random_state=42)

In [60]:
print(x11_train.shape)
print(y11_train.shape)
print(x11_test.shape)
print(y11_test.shape)

(12423, 9)
(12423,)
(5325, 9)
(5325,)


In [63]:
from sklearn.ensemble import RandomForestClassifier
m2=RandomForestClassifier()
m2.fit(x11_train,y11_train)
testprediction2=m2.predict(x11_test)
print(accuracy_score(y11_test,testprediction2))
print(confusion_matrix(y11_test,testprediction2))
print(classification_report(y11_test,testprediction2))
kfold=KFold(n_splits=5,shuffle=True)
score2=cross_val_score(m2,x11,y11,cv=kfold)
print(score2)
print(score2.mean())
print(((accuracy_score(y11_test,testprediction2))-score2.mean()))

0.9767136150234742
[[1327   12    0    0]
 [  15 1322   30    0]
 [   0   36 1287   14]
 [   0    0   17 1265]]
              precision    recall  f1-score   support

           1       0.99      0.99      0.99      1339
           2       0.96      0.97      0.97      1367
           3       0.96      0.96      0.96      1337
           4       0.99      0.99      0.99      1282

    accuracy                           0.98      5325
   macro avg       0.98      0.98      0.98      5325
weighted avg       0.98      0.98      0.98      5325

[0.97859155 0.97746479 0.97633803 0.97886729 0.98309383]
0.9788710964008904
-0.002157481377416226


In [65]:
from sklearn.ensemble import ExtraTreesClassifier
m3=ExtraTreesClassifier()
m3.fit(x11_train,y11_train)
testprediction3=m3.predict(x11_test)
print(accuracy_score(y11_test,testprediction3))
print(confusion_matrix(y11_test,testprediction3))
print(classification_report(y11_test,testprediction3))
kfold=KFold(n_splits=5,shuffle=True)
score3=cross_val_score(m3,x11,y11,cv=kfold)
print(score3)
print(score3.mean())
print(((accuracy_score(y11_test,testprediction3))-score3.mean()))

0.9780281690140845
[[1319   19    0    1]
 [  12 1326   28    1]
 [   0   24 1296   17]
 [   0    0   15 1267]]
              precision    recall  f1-score   support

           1       0.99      0.99      0.99      1339
           2       0.97      0.97      0.97      1367
           3       0.97      0.97      0.97      1337
           4       0.99      0.99      0.99      1282

    accuracy                           0.98      5325
   macro avg       0.98      0.98      0.98      5325
weighted avg       0.98      0.98      0.98      5325

[0.98140845 0.98112676 0.97887324 0.98196675 0.97661313]
0.979997666472206
-0.001969497458121472


In [66]:
from sklearn.ensemble import GradientBoostingClassifier
m4=GradientBoostingClassifier()
m4.fit(x11_train,y11_train)
testprediction4=m4.predict(x11_test)
print(accuracy_score(y11_test,testprediction4))
print(confusion_matrix(y11_test,testprediction4))
print(classification_report(y11_test,testprediction4))
kfold=KFold(n_splits=5,shuffle=True)
score4=cross_val_score(m4,x11,y11,cv=kfold)
print(score4)
print(score4.mean())
print(((accuracy_score(y11_test,testprediction4))-score4.mean()))

0.9607511737089202
[[1339    0    0    0]
 [  24 1323   19    1]
 [   0   57 1230   50]
 [   0    0   58 1224]]
              precision    recall  f1-score   support

           1       0.98      1.00      0.99      1339
           2       0.96      0.97      0.96      1367
           3       0.94      0.92      0.93      1337
           4       0.96      0.95      0.96      1282

    accuracy                           0.96      5325
   macro avg       0.96      0.96      0.96      5325
weighted avg       0.96      0.96      0.96      5325

[0.96140845 0.96225352 0.95971831 0.96534235 0.9639335 ]
0.9625312268085832
-0.0017800530996630037


In [67]:
from sklearn.ensemble import AdaBoostClassifier
m5=AdaBoostClassifier()
m5.fit(x11_train,y11_train)
testprediction5=m5.predict(x11_test)
print(accuracy_score(y11_test,testprediction5))
print(confusion_matrix(y11_test,testprediction5))
print(classification_report(y11_test,testprediction5))
kfold=KFold(n_splits=5,shuffle=True)
score5=cross_val_score(m5,x11,y11,cv=kfold)
print(score5)
print(score5.mean())
print(((accuracy_score(y11_test,testprediction5))-score5.mean()))

0.7630046948356808
[[1280   59    0    0]
 [  31 1313   20    3]
 [   0  146 1158   33]
 [   0    1  969  312]]
              precision    recall  f1-score   support

           1       0.98      0.96      0.97      1339
           2       0.86      0.96      0.91      1367
           3       0.54      0.87      0.66      1337
           4       0.90      0.24      0.38      1282

    accuracy                           0.76      5325
   macro avg       0.82      0.76      0.73      5325
weighted avg       0.82      0.76      0.74      5325

[0.77098592 0.76619718 0.76985915 0.74781629 0.76162299]
0.763296306438235
-0.00029161160255419816


In [68]:
from sklearn.ensemble import BaggingClassifier
m6=BaggingClassifier()
m6.fit(x11_train,y11_train)
testprediction6=m6.predict(x11_test)
print(accuracy_score(y11_test,testprediction6))
print(confusion_matrix(y11_test,testprediction6))
print(classification_report(y11_test,testprediction6))
kfold=KFold(n_splits=5,shuffle=True)
score6=cross_val_score(m6,x11,y11,cv=kfold)
print(score6)
print(score6.mean())
print(((accuracy_score(y11_test,testprediction6))-score6.mean()))

0.9716431924882629
[[1329   10    0    0]
 [  19 1319   29    0]
 [   0   45 1277   15]
 [   0    0   33 1249]]
              precision    recall  f1-score   support

           1       0.99      0.99      0.99      1339
           2       0.96      0.96      0.96      1367
           3       0.95      0.96      0.95      1337
           4       0.99      0.97      0.98      1282

    accuracy                           0.97      5325
   macro avg       0.97      0.97      0.97      5325
weighted avg       0.97      0.97      0.97      5325

[0.97774648 0.97126761 0.97408451 0.98140321 0.97520428]
0.9759412173236658
-0.004298024835402869


In [69]:
from sklearn.svm import SVC
m7=SVC()
m7.fit(x11_train,y11_train)
testprediction7=m7.predict(x11_test)
print(accuracy_score(y11_test,testprediction7))
print(confusion_matrix(y11_test,testprediction7))
print(classification_report(y11_test,testprediction7))
kfold=KFold(n_splits=5,shuffle=True)
score7=cross_val_score(m7,x11,y11,cv=kfold)
print(score7)
print(score7.mean())
print(((accuracy_score(y11_test,testprediction7))-score7.mean()))

0.9034741784037559
[[1246   61   31    1]
 [  16 1249   86   16]
 [   0   78 1143  116]
 [   0    6  103 1173]]
              precision    recall  f1-score   support

           1       0.99      0.93      0.96      1339
           2       0.90      0.91      0.90      1367
           3       0.84      0.85      0.85      1337
           4       0.90      0.91      0.91      1282

    accuracy                           0.90      5325
   macro avg       0.91      0.90      0.90      5325
weighted avg       0.91      0.90      0.90      5325

[0.90985915 0.89492958 0.90760563 0.90786137 0.90222598]
0.9044963429492142
-0.0010221645454583372


In [70]:
from sklearn.tree import DecisionTreeClassifier
m8=DecisionTreeClassifier()
m8.fit(x11_train,y11_train)
testprediction8=m8.predict(x11_test)
print(accuracy_score(y11_test,testprediction8))
print(confusion_matrix(y11_test,testprediction8))
print(classification_report(y11_test,testprediction8))
kfold=KFold(n_splits=5,shuffle=True)
score8=cross_val_score(m8,x11,y11,cv=kfold)
print(score8)
print(score8.mean())
print(((accuracy_score(y11_test,testprediction8))-score8.mean()))

0.9676995305164319
[[1325   14    0    0]
 [  15 1309   43    0]
 [   0   46 1274   17]
 [   0    0   37 1245]]
              precision    recall  f1-score   support

           1       0.99      0.99      0.99      1339
           2       0.96      0.96      0.96      1367
           3       0.94      0.95      0.95      1337
           4       0.99      0.97      0.98      1282

    accuracy                           0.97      5325
   macro avg       0.97      0.97      0.97      5325
weighted avg       0.97      0.97      0.97      5325

[0.96816901 0.96647887 0.96760563 0.97154128 0.97013243]
0.9687854464062481
-0.0010859158898162136


BAGGING CLASSIFIER has been selected as the best model

In [71]:
from sklearn.model_selection import GridSearchCV
parameters={'bootstrap':[True,False],'warm_start':[True,False],'n_jobs':[-1,1],'random_state':[10,12,42,50],'oob_score':[True,False]}
gridsearchcv=GridSearchCV(BaggingClassifier(),parameters,cv=5)
gridsearchcv.fit(x11_train,y11_train)                      

GridSearchCV(cv=5, estimator=BaggingClassifier(),
             param_grid={'bootstrap': [True, False], 'n_jobs': [-1, 1],
                         'oob_score': [True, False],
                         'random_state': [10, 12, 42, 50],
                         'warm_start': [True, False]})

In [72]:
gridsearchcv.best_params_

{'bootstrap': True,
 'n_jobs': -1,
 'oob_score': True,
 'random_state': 50,
 'warm_start': False}

In [74]:
best_model=BaggingClassifier(bootstrap=True,oob_score=True,n_jobs=-1,random_state=50,warm_start=False)
best_model.fit(x11_train,y11_train)
prediction=best_model.predict(x11_test)
accuracy=accuracy_score(y11_test,prediction)
print(accuracy)

0.9742723004694835


In [75]:
#SAVING THE BEST MODEL
import joblib
joblib.dump(best_model,"zomatopr.pkl")

['zomatopr.pkl']

In [76]:
reload=joblib.load('zomatopr.pkl')
reload.predict(x1_test)

array([2, 2, 2, ..., 2, 2, 2], dtype=int64)

In [77]:
import pickle
filename='zomatopr.pkl'
pickle.dump(best_model,open(filename,'wb'))
loaded_model=pickle.load(open('zomatopr.pkl','rb'))
result=loaded_model.score(x11_test,y11_test)
print(result)

0.9742723004694835


In [79]:
ds66=pd.DataFrame([loaded_model.predict(x11_test)[:],y11_test[:]])
ds66

0     1     2     3     4     5     6     7     8     9     ...  5315  \
0     3     1     3     1     4     3     4     3     2     4  ...     3   
1     3     1     3     1     4     3     4     3     2     4  ...     3   

   5316  5317  5318  5319  5320  5321  5322  5323  5324  
0     1     3     4     4     3     2     1     3     2  
1     1     3     4     4     3     2     1     3     2  

[2 rows x 5325 columns]